#tomcat config
server :
  port : 6666
  ##项目名字配置
  #servlet : 
  #  context-path : /demo
  tomcat :
    max-threads : 128
    min-spare-threads : 5
    uri-encoding : UTF-8
    #shiro 报错修改的地方
    max-connections: 200000
    max-http-post-size: 9000000
spring :
  servlet:
    multipart:
      #设置总上传的数据大小
      max-request-size: 100MB
      #单个文件大小
      maxFileSize : 30MB
      #shiro 报错修改的地方
    max-connections: 200000
    max-http-post-size: 9000000
    # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  mvc:   #静态文件
    static-path-pattern : /static/**

  datasource:
    username: hc_things
    password: hc_things12345678
    url: jdbc:mysql://122.51.219.127:3306/hc_things?
    useUnicode: true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,log4j
    logSlowSql: true



  #模板引擎
  thymeleaf:
    model: HTML5
    prefix: classpath:/pages/
    suffix: .html
    #指定编码
    encoding: utf-8
    #禁用缓存 默认false
    cache: false
  mqtt:
    client:
      id: java110-client-id
    completionTimeout: 3000
    default:
      topic: topic
    password: admin
    url: tcp://192.168.1.4:1883
    username: admin
    keepalive: 10

mybatis:
  mapper-locations: classpath:mapper/*/*Mapper.xml
  type-aliases-package: com.java110.things.entity

logging:
  level:
    com:
      example:
        mapper: debug